services:
  - type: web
    name: wealthpath-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONOPTIMIZE
        value: 2
      - key: MALLOC_ARENA_MAX
        value: 2
      - key: CHROMA_PERSIST_DIRECTORY
        value: /tmp/vector_db
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      # YOUR API keys for ALL users (MVP testing)
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false  
      - key: ENVIRONMENT
        value: production
      - key: ADMIN_EMAIL
        value: debashishroy@gmail.com
      # MVP settings
      - key: MVP_MODE
        value: true
      - key: LLM_DEFAULT_PROVIDER
        value: gemini
    healthCheckPath: /health