"""Fix investment preferences numeric fields

Revision ID: 01c2eac84705
Revises: 01545a03be48
Create Date: 2025-09-17 00:50:15.579273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01c2eac84705'
down_revision = '01545a03be48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_goals_snapshot_id', table_name='snapshot_goals')
    op.drop_table('snapshot_goals')
    op.drop_index('ix_snapshot_entries_snapshot_id', table_name='snapshot_entries')
    op.drop_table('snapshot_entries')
    op.drop_index('ix_financial_snapshots_snapshot_date', table_name='financial_snapshots')
    op.drop_index('ix_financial_snapshots_user_id', table_name='financial_snapshots')
    op.drop_table('financial_snapshots')
    op.alter_column('goals_history', 'history_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # Convert boolean to numeric with proper casting
    op.execute("""
        ALTER TABLE user_investment_preferences
        ALTER COLUMN alternative_investment_interest
        TYPE numeric(5,2)
        USING CASE
            WHEN alternative_investment_interest = true THEN 50.0
            WHEN alternative_investment_interest = false THEN 0.0
            ELSE NULL
        END
    """)

    op.execute("""
        ALTER TABLE user_investment_preferences
        ALTER COLUMN individual_stock_tolerance
        TYPE numeric(5,2)
        USING CASE
            WHEN individual_stock_tolerance = true THEN 50.0
            WHEN individual_stock_tolerance = false THEN 0.0
            ELSE NULL
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_investment_preferences', 'individual_stock_tolerance',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('user_investment_preferences', 'alternative_investment_interest',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('goals_history', 'history_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('financial_snapshots',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('financial_snapshots_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('net_worth', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_assets', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_liabilities', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('monthly_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('monthly_expenses', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('savings_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employment_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='financial_snapshots_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='financial_snapshots_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_financial_snapshots_user_id', 'financial_snapshots', ['user_id'], unique=False)
    op.create_index('ix_financial_snapshots_snapshot_date', 'financial_snapshots', ['snapshot_date'], unique=False)
    op.create_table('snapshot_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['financial_snapshots.id'], name='snapshot_entries_snapshot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='snapshot_entries_pkey')
    )
    op.create_index('ix_snapshot_entries_snapshot_id', 'snapshot_entries', ['snapshot_id'], unique=False)
    op.create_table('snapshot_goals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('target_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completion_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['financial_snapshots.id'], name='snapshot_goals_snapshot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='snapshot_goals_pkey')
    )
    op.create_index('ix_snapshot_goals_snapshot_id', 'snapshot_goals', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###