"""Add chat intelligence table

Revision ID: 0a9c004b
Revises: enhance_tax_info_table
Create Date: 2025-08-30 18:33:45.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a9c004b'
down_revision = 'enhance_tax_info_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_intelligence',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('key_decisions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('financial_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics_discussed', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('conversation_turns', sa.Integer(), nullable=False),
    sa.Column('last_intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_intelligence_id', 'chat_intelligence', ['id'])
    op.create_index('ix_chat_intelligence_session_id', 'chat_intelligence', ['session_id'])
    op.create_index('ix_chat_intelligence_user_id', 'chat_intelligence', ['user_id'])
    op.create_index('ix_chat_intelligence_user_id_session_id', 'chat_intelligence', ['user_id', 'session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_intelligence_user_id_session_id', table_name='chat_intelligence')
    op.drop_index('ix_chat_intelligence_user_id', table_name='chat_intelligence')
    op.drop_index('ix_chat_intelligence_session_id', table_name='chat_intelligence')
    op.drop_index('ix_chat_intelligence_id', table_name='chat_intelligence')
    op.drop_table('chat_intelligence')
    # ### end Alembic commands ###