"""Add max_401k_contribution to user_benefits

Revision ID: 0ae4f242fecf
Revises: f12e4649c81f
Create Date: 2025-09-06 17:37:53.299512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae4f242fecf'
down_revision = 'f12e4649c81f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_benefits', sa.Column('max_401k_contribution', sa.Numeric(12, 2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_benefits', 'max_401k_contribution')
    # ### end Alembic commands ###