"""Add ADVISOR+ fields to user_profiles

Revision ID: 1444dadba9de
Revises: f96632089afd
Create Date: 2025-08-21 16:01:49.328292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1444dadba9de'
down_revision = 'f96632089afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('retirement_age', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('retirement_goal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('emergency_fund_months', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('social_security_age', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('social_security_monthly', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('risk_tolerance_score', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferences')
    op.drop_column('user_profiles', 'risk_tolerance_score')
    op.drop_column('user_profiles', 'social_security_monthly')
    op.drop_column('user_profiles', 'social_security_age')
    op.drop_column('user_profiles', 'emergency_fund_months')
    op.drop_column('user_profiles', 'retirement_goal')
    op.drop_column('user_profiles', 'retirement_age')
    # ### end Alembic commands ###