"""Add notes field to user_profiles

Revision ID: 306ad2796314
Revises: f5feecea17cd
Create Date: 2025-08-20 02:49:34.373623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306ad2796314'
down_revision = 'f5feecea17cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'notes')
    # ### end Alembic commands ###