"""Add chat_sessions and chat_messages tables

Revision ID: 5beed2bb881f
Revises: 0ae4f242fecf
Create Date: 2025-09-06 17:52:04.646733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5beed2bb881f'
down_revision = '0ae4f242fecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_benefits', 'max_401k_contribution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_benefits', sa.Column('max_401k_contribution', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###