"""add_intelligence_tables

Revision ID: 6ab6b908bdb7
Revises: 6fbfb13f9a53
Create Date: 2025-08-14 23:09:00.511869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ab6b908bdb7'
down_revision = '6fbfb13f9a53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_progress', 'progress_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_goal_progress_goal_id', table_name='goal_progress')
    op.drop_index('idx_goal_progress_recorded_at', table_name='goal_progress')
    op.create_index(op.f('ix_goal_progress_goal_id'), 'goal_progress', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_progress_recorded_at'), 'goal_progress', ['recorded_at'], unique=False)
    op.alter_column('goal_relationships', 'relationship_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goals', 'goal_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goals', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_goals_category', table_name='goals')
    op.drop_index('idx_goals_priority', table_name='goals')
    op.drop_index('idx_goals_target_date', table_name='goals')
    op.drop_index('idx_goals_user_status', table_name='goals')
    op.create_index(op.f('ix_goals_category'), 'goals', ['category'], unique=False)
    op.create_index(op.f('ix_goals_priority'), 'goals', ['priority'], unique=False)
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_index(op.f('ix_goals_target_date'), 'goals', ['target_date'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.alter_column('goals_history', 'history_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_goals_history_changed_at', table_name='goals_history')
    op.drop_index('idx_goals_history_goal_id', table_name='goals_history')
    op.create_index(op.f('ix_goals_history_changed_at'), 'goals_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_goals_history_goal_id'), 'goals_history', ['goal_id'], unique=False)
    op.create_foreign_key(None, 'user_activity_logs', 'users', ['user_id'], ['id'])
    op.alter_column('user_preferences', 'preference_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_preferences', 'notification_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_preferences', 'goal_categories_enabled',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('user_preferences_user_id_key', 'user_preferences', type_='unique')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_unique_constraint('user_preferences_user_id_key', 'user_preferences', ['user_id'])
    op.alter_column('user_preferences', 'goal_categories_enabled',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('\'["retirement", "emergency_fund", "education", "real_estate"]\'::jsonb'),
               existing_nullable=False)
    op.alter_column('user_preferences', 'notification_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('user_preferences', 'preference_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'user_activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_goals_history_goal_id'), table_name='goals_history')
    op.drop_index(op.f('ix_goals_history_changed_at'), table_name='goals_history')
    op.create_index('idx_goals_history_goal_id', 'goals_history', ['goal_id'], unique=False)
    op.create_index('idx_goals_history_changed_at', 'goals_history', ['changed_at'], unique=False)
    op.alter_column('goals_history', 'history_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_target_date'), table_name='goals')
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    op.drop_index(op.f('ix_goals_priority'), table_name='goals')
    op.drop_index(op.f('ix_goals_category'), table_name='goals')
    op.create_index('idx_goals_user_status', 'goals', ['user_id', 'status'], unique=False)
    op.create_index('idx_goals_target_date', 'goals', ['target_date'], unique=False)
    op.create_index('idx_goals_priority', 'goals', ['priority'], unique=False)
    op.create_index('idx_goals_category', 'goals', ['category'], unique=False)
    op.alter_column('goals', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('goals', 'goal_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('goal_relationships', 'relationship_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_goal_progress_recorded_at'), table_name='goal_progress')
    op.drop_index(op.f('ix_goal_progress_goal_id'), table_name='goal_progress')
    op.create_index('idx_goal_progress_recorded_at', 'goal_progress', ['recorded_at'], unique=False)
    op.create_index('idx_goal_progress_goal_id', 'goal_progress', ['goal_id'], unique=False)
    op.alter_column('goal_progress', 'progress_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###