"""Initial migration

Revision ID: af18b908f777
Revises: 
Create Date: 2025-08-10 03:05:32.453489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af18b908f777'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('control_variant', sa.String(length=50), nullable=False),
    sa.Column('test_variants', sa.Text(), nullable=False),
    sa.Column('traffic_allocation', sa.Text(), nullable=False),
    sa.Column('primary_metric', sa.String(length=100), nullable=False),
    sa.Column('secondary_metrics', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_sample_size', sa.Integer(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('statistical_significance', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_experiments_experiment_id'), 'ab_test_experiments', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_ab_test_experiments_id'), 'ab_test_experiments', ['id'], unique=False)
    op.create_table('feature_importance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.Enum('target_setting', 'portfolio_optimization', 'behavioral_prediction', 'gap_analysis', 'risk_assessment', name='modeltype'), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_category', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('correlation_direction', sa.String(length=10), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_importance_id'), 'feature_importance', ['id'], unique=False)
    op.create_index(op.f('ix_feature_importance_model_type'), 'feature_importance', ['model_type'], unique=False)
    op.create_table('model_performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.Enum('target_setting', 'portfolio_optimization', 'behavioral_prediction', 'gap_analysis', 'risk_assessment', name='modeltype'), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recall_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('mae', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mse', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('custom_metrics', sa.Text(), nullable=True),
    sa.Column('test_set_size', sa.Integer(), nullable=True),
    sa.Column('test_set_description', sa.String(length=200), nullable=True),
    sa.Column('cross_validation_folds', sa.Integer(), nullable=True),
    sa.Column('evaluation_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_metrics_evaluation_date'), 'model_performance_metrics', ['evaluation_date'], unique=False)
    op.create_index(op.f('ix_model_performance_metrics_id'), 'model_performance_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_model_performance_metrics_model_type'), 'model_performance_metrics', ['model_type'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_logs_action'), 'user_activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_id'), 'user_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('risk_tolerance', sa.Integer(), nullable=False),
    sa.Column('investment_experience', sa.String(length=20), nullable=False),
    sa.Column('annual_income', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('data_sharing_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('analytics_consent', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'deleted', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('checking', 'savings', 'investment', 'retirement', 'credit', 'loan', 'mortgage', 'crypto', name='accounttype'), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number_masked', sa.String(length=20), nullable=True),
    sa.Column('plaid_account_id', sa.String(length=100), nullable=True),
    sa.Column('plaid_item_id', sa.String(length=100), nullable=True),
    sa.Column('external_account_id', sa.String(length=100), nullable=True),
    sa.Column('data_quality', sa.Enum('DQ1', 'DQ2', 'DQ3', 'DQ4', name='dataquality'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_plaid_account_id'), 'financial_accounts', ['plaid_account_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_user_id'), 'financial_accounts', ['user_id'], unique=False)
    op.create_table('financial_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.Enum('early_retirement', 'home_purchase', 'education', 'emergency_fund', 'debt_payoff', 'custom', name='goaltype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monthly_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('feasibility_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('success_probability', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'achieved', 'paused', 'abandoned', name='goalstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_goals_goal_type'), 'financial_goals', ['goal_type'], unique=False)
    op.create_index(op.f('ix_financial_goals_id'), 'financial_goals', ['id'], unique=False)
    op.create_index(op.f('ix_financial_goals_user_id'), 'financial_goals', ['user_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.Enum('target_setting', 'portfolio_optimization', 'behavioral_prediction', 'gap_analysis', 'risk_assessment', name='modeltype'), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='predictionstatus'), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('human_feedback_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_id'), 'model_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_model_predictions_input_hash'), 'model_predictions', ['input_hash'], unique=False)
    op.create_index(op.f('ix_model_predictions_model_type'), 'model_predictions', ['model_type'], unique=False)
    op.create_index(op.f('ix_model_predictions_user_id'), 'model_predictions', ['user_id'], unique=False)
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liquid_assets', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('investment_assets', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('real_estate_assets', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_assets', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calculation_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('data_quality_score', sa.String(length=3), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_worth_snapshots_id'), 'net_worth_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_net_worth_snapshots_snapshot_date'), 'net_worth_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_net_worth_snapshots_user_id'), 'net_worth_snapshots', ['user_id'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.Enum('page_view', 'button_click', 'form_submit', 'goal_create', 'goal_update', 'recommendation_view', 'recommendation_accept', 'recommendation_decline', 'calculation_request', name='interactiontype'), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('element_id', sa.String(length=100), nullable=True),
    sa.Column('element_text', sa.String(length=200), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser_name', sa.String(length=50), nullable=True),
    sa.Column('screen_resolution', sa.String(length=20), nullable=True),
    sa.Column('interaction_data', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('scroll_depth', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.String(length=50), nullable=True),
    sa.Column('variant_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_id'), 'user_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_user_interactions_interaction_type'), 'user_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_user_interactions_session_id'), 'user_interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_timestamp'), 'user_interactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_interactions_user_id'), 'user_interactions', ['user_id'], unique=False)
    op.create_table('account_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_type', sa.String(length=20), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('data_quality', sa.Enum('DQ1', 'DQ2', 'DQ3', 'DQ4', name='dataquality'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_balances_account_id'), 'account_balances', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_balances_as_of_date'), 'account_balances', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_account_balances_id'), 'account_balances', ['id'], unique=False)
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='actionpriority'), nullable=False),
    sa.Column('impact_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('difficulty_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('target_start_date', sa.DateTime(), nullable=True),
    sa.Column('target_completion_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', name='actionstatus'), nullable=False),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plans_action_type'), 'action_plans', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_plans_goal_id'), 'action_plans', ['goal_id'], unique=False)
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_table('financial_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('assets', 'liabilities', 'income', 'expenses', name='entrycategory'), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('one_time', 'daily', 'weekly', 'monthly', 'quarterly', 'annually', name='frequencytype'), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Enum('DQ1', 'DQ2', 'DQ3', 'DQ4', name='dataquality'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('plaid_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_entries_account_id'), 'financial_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_entries_category'), 'financial_entries', ['category'], unique=False)
    op.create_index(op.f('ix_financial_entries_entry_date'), 'financial_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_financial_entries_external_transaction_id'), 'financial_entries', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_financial_entries_id'), 'financial_entries', ['id'], unique=False)
    op.create_index(op.f('ix_financial_entries_user_id'), 'financial_entries', ['user_id'], unique=False)
    op.create_table('goal_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_achieved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_milestones_goal_id'), 'goal_milestones', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_milestones_id'), 'goal_milestones', ['id'], unique=False)
    op.create_table('goal_performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('variance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_target_date', sa.DateTime(), nullable=True),
    sa.Column('updated_success_probability', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('days_ahead_behind', sa.Integer(), nullable=False),
    sa.Column('measurement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_performance_metrics_goal_id'), 'goal_performance_metrics', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_performance_metrics_id'), 'goal_performance_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_goal_performance_metrics_measurement_date'), 'goal_performance_metrics', ['measurement_date'], unique=False)
    op.create_table('goal_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.Column('projected_end_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('projected_end_date', sa.DateTime(), nullable=True),
    sa.Column('required_monthly_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('success_probability', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_scenarios_goal_id'), 'goal_scenarios', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_scenarios_id'), 'goal_scenarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_scenarios_id'), table_name='goal_scenarios')
    op.drop_index(op.f('ix_goal_scenarios_goal_id'), table_name='goal_scenarios')
    op.drop_table('goal_scenarios')
    op.drop_index(op.f('ix_goal_performance_metrics_measurement_date'), table_name='goal_performance_metrics')
    op.drop_index(op.f('ix_goal_performance_metrics_id'), table_name='goal_performance_metrics')
    op.drop_index(op.f('ix_goal_performance_metrics_goal_id'), table_name='goal_performance_metrics')
    op.drop_table('goal_performance_metrics')
    op.drop_index(op.f('ix_goal_milestones_id'), table_name='goal_milestones')
    op.drop_index(op.f('ix_goal_milestones_goal_id'), table_name='goal_milestones')
    op.drop_table('goal_milestones')
    op.drop_index(op.f('ix_financial_entries_user_id'), table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_id'), table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_external_transaction_id'), table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_entry_date'), table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_category'), table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_account_id'), table_name='financial_entries')
    op.drop_table('financial_entries')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_goal_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_action_type'), table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_account_balances_id'), table_name='account_balances')
    op.drop_index(op.f('ix_account_balances_as_of_date'), table_name='account_balances')
    op.drop_index(op.f('ix_account_balances_account_id'), table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_index(op.f('ix_user_interactions_user_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_timestamp'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_session_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_interaction_type'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_net_worth_snapshots_user_id'), table_name='net_worth_snapshots')
    op.drop_index(op.f('ix_net_worth_snapshots_snapshot_date'), table_name='net_worth_snapshots')
    op.drop_index(op.f('ix_net_worth_snapshots_id'), table_name='net_worth_snapshots')
    op.drop_table('net_worth_snapshots')
    op.drop_index(op.f('ix_model_predictions_user_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_model_type'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_input_hash'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_financial_goals_user_id'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_id'), table_name='financial_goals')
    op.drop_index(op.f('ix_financial_goals_goal_type'), table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index(op.f('ix_financial_accounts_user_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_plaid_account_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_action'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_model_performance_metrics_model_type'), table_name='model_performance_metrics')
    op.drop_index(op.f('ix_model_performance_metrics_id'), table_name='model_performance_metrics')
    op.drop_index(op.f('ix_model_performance_metrics_evaluation_date'), table_name='model_performance_metrics')
    op.drop_table('model_performance_metrics')
    op.drop_index(op.f('ix_feature_importance_model_type'), table_name='feature_importance')
    op.drop_index(op.f('ix_feature_importance_id'), table_name='feature_importance')
    op.drop_table('feature_importance')
    op.drop_index(op.f('ix_ab_test_experiments_id'), table_name='ab_test_experiments')
    op.drop_index(op.f('ix_ab_test_experiments_experiment_id'), table_name='ab_test_experiments')
    op.drop_table('ab_test_experiments')
    # ### end Alembic commands ###