"""
CI Pipeline for wpa
Auto-generated by Claude Code Orchestrator
"""

import subprocess
import json
from pathlib import Path

def run_tests():
    cmd = "pytest --cov=. tests/"
    result = subprocess.run(cmd.split(), capture_output=True, text=True)
    return result.returncode == 0

def run_lint():
    cmd = "ruff check ."
    result = subprocess.run(cmd.split(), capture_output=True, text=True)
    return result.returncode == 0

def run_security():
    cmd = "bandit -r . && safety check"
    result = subprocess.run(cmd.split(), capture_output=True, text=True)
    return result.returncode == 0

if __name__ == "__main__":
    print("🚀 Running CI pipeline...")

    results = {
        "tests": run_tests(),
        "lint": run_lint(),
        "security": run_security()
    }

    print(f"Results: {results}")
